---
# Mothership calls a local AWS CLI inside a Basic container for AWS deployment tasks.
# We preconfigure a virtualenv with AWS CLI to avoid upstream dependencies.

- name: Stat
  ansible.builtin.stat:
    path: "{{ codeship_venv }}"
  register: directory

- name: Install virtualenv (Focal)
  ansible.builtin.pip:
    name: virtualenv
    state: present
  when:
    - not directory.stat.exists
    - ansible_distribution_release == 'focal'

- name: Install virtualenv (Noble)
  ansible.builtin.apt:
    name: python3-virtualenv
    state: present
    install_recommends: false
  when:
    - not directory.stat.exists
    - ansible_distribution_release == 'noble'

- name: Create virtualenv
  ansible.builtin.command: virtualenv --python={{ codeship_python }} {{ codeship_venv }}
  become: true
  become_user: "{{ aws_user }}"
  when: not directory.stat.exists

- name: Install AWS CLI into virtualenv
  ansible.builtin.pip:
    name: awscli
    virtualenv: "{{ codeship_venv }}"
  become: true
  become_user: "{{ aws_user }}"
  when: not directory.stat.exists

- name: Uninstall virtualenv (Focal)
  ansible.builtin.pip:
    name: virtualenv
    state: absent
  when:
    - not directory.stat.exists
    - ansible_distribution_release == 'focal'

- name: Uninstall virtualenv (Noble)
  ansible.builtin.apt:
    name: python3-virtualenv
    state: absent
  when:
    - not directory.stat.exists
    - ansible_distribution_release == 'noble'

- name: Move scripts into the container
  ansible.posix.synchronize:
    src: "{{ role_path }}/deployment/scripts/"
    dest: "{{ aws_home }}/bin/"
    use_ssh_args: true
    owner: false
    group: false
  become: true
  become_user: "{{ aws_user }}"

- name: Fix file permissions
  ansible.builtin.file:
    dest: "{{ aws_home }}/bin/"
    owner: "{{ aws_user }}"
    recurse: true
